openapi: 3.0.0
info:
  title: Peregrinno's Delivery API | Ruby + Sinatra 游눑
  description: API para sistema de delivery com gest칚o de pedidos, produtos e usu치rios
  version: 1.1.0

servers:
  - url: http://localhost:4567
    description: Servidor de desenvolvimento

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string

    Success:
      type: object
      properties:
        data:
          type: object
        status:
          type: integer
          default: 200

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string

    TokenResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            token:
              type: string
        status:
          type: integer

    CustomerRegister:
      type: object
      required:
        - email
        - name
        - password
      properties:
        email:
          type: string
        name:
          type: string
        password:
          type: string

    Product:
      type: object
      required:
        - name
        - value
      properties:
        id:
          type: string
        name:
          type: string
        value:
          type: number
          format: float

    Order:
      type: object
      properties:
        id:
          type: string
        customer:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            email:
              type: string
        total:
          type: number
          format: float
        status:
          type: string
          enum:
            [
              "Em analise",
              "Em preparo",
              "Pronto",
              "Enviado",
              "Entregue",
              "Cancelado",
            ]
        date:
          type: string
          format: date-time
        items:
          type: array
          items:
            type: object
            properties:
              product:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
              sub_total:
                type: number
                format: float

paths:
  /auth/login:
    post:
      tags:
        - Autentica칞칚o
      summary: Login de usu치rio admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login bem sucedido
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "401":
          description: Credenciais inv치lidas

  /auth/customer/login:
    post:
      tags:
        - Autentica칞칚o
      summary: Login de cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login bem sucedido
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "401":
          description: Credenciais inv치lidas

  /first-user:
    post:
      tags:
        - Autentica칞칚o
      summary: Cria o primeiro usu치rio admin do sistema
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Usu치rio criado com sucesso
        "400":
          description: J치 existe um usu치rio cadastrado

  /admin/users:
    get:
      tags:
        - Admin - Usu치rios
      summary: Lista todos os usu치rios
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Lista de usu치rios
        "401":
          description: N칚o autorizado

    post:
      tags:
        - Admin - Usu치rios
      summary: Cria novo usu치rio
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - username
                - password
              properties:
                email:
                  type: string
                username:
                  type: string
                password:
                  type: string
                permissions:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: Usu치rio criado com sucesso
        "401":
          description: N칚o autorizado

  /admin/users/{id}:
    put:
      tags:
        - Admin - Usu치rios
      summary: Atualiza usu치rio
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                username:
                  type: string
                password:
                  type: string
                active:
                  type: boolean
                permissions:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: Usu치rio atualizado com sucesso
        "401":
          description: N칚o autorizado

    delete:
      tags:
        - Admin - Usu치rios
      summary: Remove um usu치rio
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Usu치rio removido com sucesso
        "401":
          description: N칚o autorizado

  /admin/products:
    get:
      tags:
        - Admin - Produtos
      summary: Lista todos os produtos
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Lista de produtos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    value:
                      type: number
        "401":
          description: N칚o autorizado

    post:
      tags:
        - Admin - Produtos
      summary: Cria um novo produto
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                value:
                  type: number
      responses:
        "200":
          description: Produto criado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"
        "401":
          description: N칚o autorizado

  /admin/products/{id}:
    put:
      tags:
        - Admin - Produtos
      summary: Atualiza um produto
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                value:
                  type: number
      responses:
        "200":
          description: Produto atualizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"
        "401":
          description: N칚o autorizado
        "404":
          description: Produto n칚o encontrado

    delete:
      tags:
        - Admin - Produtos
      summary: Remove um produto
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Produto removido
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"
        "401":
          description: N칚o autorizado
        "404":
          description: Produto n칚o encontrado

  /admin/orders:
    get:
      tags:
        - Admin - Pedidos
      summary: Lista todos os pedidos
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Lista de pedidos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    customer:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        email:
                          type: string
                    total:
                      type: number
                    status:
                      type: string
                      enum: [pending, preparing, shipping, delivered, canceled]
                    date:
                      type: string
                      format: date-time
                    items:
                      type: array
                      items:
                        type: object
                        properties:
                          product:
                            type: object
                            properties:
                              id:
                                type: string
                              name:
                                type: string
                          sub_total:
                            type: number
        "401":
          description: N칚o autorizado

  /admin/orders/{id}/status:
    put:
      tags:
        - Admin - Pedidos
      summary: Atualiza o status de um pedido
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [pending, preparing, shipping, delivered, canceled]
      responses:
        "200":
          description: Status atualizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"
        "400":
          description: Status inv치lido
        "401":
          description: N칚o autorizado
        "404":
          description: Pedido n칚o encontrado

  /customer/register:
    post:
      tags:
        - Clientes
      summary: Registro de novo cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerRegister"
      responses:
        "200":
          description: Cliente registrado com sucesso
        "400":
          description: Erro na valida칞칚o dos dados

  /customer/orders:
    get:
      tags:
        - Clientes
      summary: Lista os pedidos do cliente
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Lista de pedidos do cliente
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    total:
                      type: number
                    status:
                      type: string
                      enum: [pending, preparing, shipping, delivered, canceled]
                    date:
                      type: string
                      format: date-time
                    items:
                      type: array
                      items:
                        type: object
                        properties:
                          product:
                            type: object
                            properties:
                              name:
                                type: string
                          sub_total:
                            type: number
        "401":
          description: N칚o autorizado

  /products:
    get:
      tags:
        - Produtos
      summary: Lista todos os produtos dispon칤veis
      responses:
        "200":
          description: Lista de produtos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"

  /orders:
    post:
      tags:
        - Pedidos
      summary: Cria um novo pedido
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                delivery_address:
                  type: string
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      product_id:
                        type: string
                      quantity:
                        type: integer
                        minimum: 1
      responses:
        "200":
          description: Pedido criado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"
        "400":
          description: Dados inv치lidos
        "401":
          description: N칚o autorizado
